# Generated by Django 5.2.8 on 2025-11-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_question', models.TextField()),
                ('theme_name', models.CharField(max_length=255)),
                ('extractions_context', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('central_codes', models.JSONField(blank=True, default=list)),
                ('key_citations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('INTERPRETATION_COMPLETED', 'Interpretación Finalizada')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESEARCHER', 'Investigador'), ('COPILOT', 'Copilot'), ('SYSTEM', 'Sistema')], max_length=20)),
                ('message', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_traces', to='interpretation.interpretationcontext')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterpretativeProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition_text', models.TextField()),
                ('supporting_narrative', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REFINED', 'Refinada'), ('FINAL', 'Final')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('conversation_trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions', to='interpretation.conversationtrace')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions', to=settings.AUTH_USER_MODEL)),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='interpretation.subtheme')),
            ],
        ),
        migrations.AddField(
            model_name='interpretationcontext',
            name='subtheme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='interpretation.subtheme'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('research_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='interpretation.theme'),
        ),
    ]
