# Generated by Django 5.2.8 on 2025-11-13 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0001_initial'),
        ('project', '0004_project_research_framework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_type', models.CharField(choices=[('CODE_NORMALIZATION', 'Normalización de Códigos'), ('THEME_DISCOVERY', 'Descubrimiento de Temas')], max_length=30)),
                ('ai_proposal', models.JSONField(default=dict)),
                ('researcher_modifications', models.JSONField(default=dict)),
                ('final_result', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_traces', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_traces', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Analysis Traces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeNormalizationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_code', models.CharField(max_length=255)),
                ('original_codes', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('ACCEPTED', 'Aceptada por el Investigador'), ('REJECTED', 'Rechazada'), ('MODIFIED', 'Modificada por el Investigador')], default='PENDING', max_length=20)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalization_proposals', to='project.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_normalizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InitialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_codes', to='project.project')),
            ],
            options={
                'ordering': ['-frequency', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('original_codes', models.JSONField(default=list)),
                ('research_question_focus', models.CharField(blank=True, help_text='RQ a la que responde este código (ej: RQ1, RQ2)', max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_codes', to='project.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_codes', to='interpretation.codenormalizationproposal')),
            ],
            options={
                'ordering': ['research_question_focus', '-frequency', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ThemeDiscoveryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=255)),
                ('theme_description', models.TextField(blank=True)),
                ('research_question_focus', models.CharField(blank=True, max_length=100)),
                ('proposed_subthemes', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('ACCEPTED', 'Aceptada'), ('MODIFIED', 'Modificada por el Investigador'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('codes_used', models.ManyToManyField(related_name='theme_proposals', to='interpretation.normalizedcode')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_proposals', to='project.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theme_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
