# Generated by Django 5.2.8 on 2026-01-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0001_initial'),
        ('project', '0003_membership_workload_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='project.project'),
        ),
    ]
