# Generated by Django 5.2.8 on 2026-01-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0002_theme_project'),
        ('project', '0003_membership_workload_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_phase', to='project.project')),
            ],
            options={
                'verbose_name': 'Interpretation Phase',
                'verbose_name_plural': 'Interpretation Phases',
                'db_table': 'interpretation_phase',
            },
        ),
    ]
