# Generated by Django 5.2.8 on 2026-01-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0003_interpretationphase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interpretationphase',
            table=None,
        ),
    ]
