# Generated by Django 5.2.8 on 2025-12-03 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPhase',
            fields=[
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='design_phase', serialize=False, to='project.project')),
                ('current_stage', models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalized')], default='RQ_CREATION', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EligibilityCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('motivation', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('INCLUSION', 'Inclusion'), ('EXCLUSION', 'Exclusion')], max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='design.designphase')),
                ('last_modified_by', models.ForeignKey(help_text='User who last modified the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_criteria', to=settings.AUTH_USER_MODEL)),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(help_text='User who reviewed the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_criteria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True)),
                ('design_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='design.designphase')),
            ],
            options={
                'unique_together': {('design_phase', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to Send'), ('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('framework_fields', models.JSONField(default=dict)),
                ('design_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='design.designphase')),
                ('last_modified_by', models.ForeignKey(help_text='User who last modified the research question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_questions', to=settings.AUTH_USER_MODEL)),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_questions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(help_text='Owner who reviewed the research question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('final_search_string', models.TextField(blank=True)),
                ('json_definition', models.JSONField(default=dict)),
                ('total_studies_found', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created the strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='User who last modified the strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_strategies', to=settings.AUTH_USER_MODEL)),
                ('research_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_strategies', to='design.researchquestion')),
                ('reviewed_by', models.ForeignKey(help_text='Who reviewed the search strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.projectkeyword')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='design.searchstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_terms', to='design.searchstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='SearchStrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('final_search_string', models.TextField()),
                ('json_definition', models.JSONField(default=dict)),
                ('total_found', models.PositiveIntegerField(default=0, help_text='Number of studies found with this strategy')),
                ('metadata_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='design.searchstrategy')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('strategy', 'version_number')},
            },
        ),
    ]
