# Generated by Django 5.2.7 on 2025-10-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PICO', 'PICO'), ('PEO', 'PEO'), ('PCC', 'PCC')], max_length=10, unique=True)),
                ('fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_question', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to Send'), ('SUGGESTED', 'Suggested'), ('SUGGEST_REJECT', 'Suggest Reject'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='project.project')),
                ('research_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='design.researchframework')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_questions', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='project.stage')),
            ],
        ),
    ]
