# Generated by Django 5.2.8 on 2025-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstrategyversion',
            name='justification',
            field=models.TextField(blank=True, help_text='Justification for approval/rejection', null=True),
        ),
    ]
