# Generated by Django 5.2.8 on 2025-12-08 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriterion',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligibilitycriterion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_criteria', to=settings.AUTH_USER_MODEL),
        ),
    ]
