# Generated by Django 5.2.8 on 2025-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_eligibilitycriterion_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriterion',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
