# Generated by Django 5.2.8 on 2025-12-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_searchstrategyversion_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='designphase',
            name='fecha_inicio_creacion_pregunta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
