# Generated by Django 5.2.7 on 2025-10-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_researchquestion_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='motivation',
            field=models.TextField(blank=True),
        ),
    ]
