# Generated by Django 5.2.8 on 2026-01-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_designphase_fecha_inicio_creacion_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designphase',
            name='fecha_inicio_creacion_pregunta',
        ),
        migrations.CreateModel(
            name='DesignStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalized')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='design.designphase')),
            ],
            options={
                'verbose_name': 'Stage Execution Log',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DesignStagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalized')], max_length=20)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_stages', to='design.designphase')),
            ],
            options={
                'verbose_name': 'Stage Plan',
                'ordering': ['planned_start_date'],
                'unique_together': {('phase', 'stage')},
            },
        ),
    ]
