# Generated by Django 5.2.7 on 2025-10-28 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_researchquestion_motivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchframework',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_frameworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchframework',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchframework',
            name='total_fields',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchframework',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='researchframework',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='researchframework',
            unique_together={('name', 'created_by')},
        ),
    ]
