# Generated by Django 5.2.8 on 2025-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_eligibilitycriterion_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstrategyversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
