# Generated by Django 5.2.7 on 2025-10-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_researchframework_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='framework_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
