# Generated by Django 5.2.7 on 2025-10-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_researchquestion_framework_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='researchquestion',
            name='stage',
        ),
    ]
