# Generated by Django 5.2.7 on 2025-11-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_remove_researchquestion_project_and_more'),
        ('project', '0002_stage_due_time_stage_opened_by_alter_stage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='project.project'),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='project.stage'),
        ),
    ]
