# Generated by Django 5.2.8 on 2025-11-09 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_researchquestion_project_researchquestion_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchframework',
            old_name='created_by',
            new_name='assigned_by',
        ),
        migrations.AlterUniqueTogether(
            name='researchframework',
            unique_together={('name', 'assigned_by')},
        ),
    ]
