# Generated by Django 5.2.8 on 2025-11-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_eligibilitycriterion_delete_eligibilitycriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('final_search_string', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_strategies', to='design.researchquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='design.searchstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_terms', to='design.searchstrategy')),
            ],
        ),
    ]
