# Generated by Django 5.2.8 on 2025-11-17 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_searchstrategy_keyword_exclusionterm'),
        ('project', '0004_project_research_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_keywords', to='project.project')),
            ],
            options={
                'unique_together': {('project', 'term')},
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='project_keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.projectkeyword'),
        ),
    ]
