# Generated by Django 5.2.8 on 2025-11-17 21:05

from django.db import migrations


def populate_project_keywords(apps, schema_editor):
    """
    Copia datos de los antiguos campos 'term' y 'synonyms' al nuevo
    modelo ProjectKeyword y lo enlaza. Elimina los Keyword huérfanos.
    """
    Keyword = apps.get_model('design', 'Keyword')
    ProjectKeyword = apps.get_model('design', 'ProjectKeyword')

    # Usamos .iterator() para procesar eficientemente tablas grandes
    for keyword in Keyword.objects.all().iterator():
        # Verificamos que el término no sea nulo ni solo espacios en blanco
        if keyword.term and keyword.term.strip():
            project = keyword.strategy.research_question.project

            project_keyword_obj, created = ProjectKeyword.objects.get_or_create(
                project=project,
                term=keyword.term.strip().lower(),
                defaults={'synonyms': keyword.synonyms or ''}
            )

            keyword.project_keyword = project_keyword_obj
            keyword.save(update_fields=['project_keyword'])
        else:
            # Si el keyword no tiene un término válido, es un dato huérfano. Lo eliminamos.
            keyword.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_projectkeyword_keyword_project_keyword'),
    ]

    operations = [
        migrations.RunPython(populate_project_keywords, reverse_code=migrations.RunPython.noop),
    ]
