# Generated by Django 5.2.8 on 2025-11-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_populate_project_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='term',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='project_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.projectkeyword'),
        ),
    ]
