# Generated by Django 5.2.8 on 2025-11-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_remove_keyword_synonyms_remove_keyword_term_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='researchframework',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='researchframework',
            name='assigned_by',
        ),
    ]
