# Generated by Django 5.2.8 on 2025-11-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_alter_researchframework_unique_together_and_more'),
        ('project', '0005_remove_stage_closed_by_remove_stage_opened_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='research_framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='project.researchframework'),
        ),
        migrations.RenameField(
            model_name='researchquestion',
            old_name='suggested_question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='researchquestion',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='researchquestion',
            name='suggester',
        ),
        migrations.DeleteModel(
            name='ResearchFramework',
        ),
    ]
