# Generated by Django 5.2.8 on 2025-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_alter_researchquestion_research_framework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='framework_fields',
            field=models.JSONField(default=dict),
        ),
    ]
