# Generated by Django 5.2.8 on 2025-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_alter_researchquestion_framework_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='justification',
            field=models.TextField(),
        ),
    ]
