# Generated by Django 5.2.8 on 2025-11-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_alter_researchquestion_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
