# Generated by Django 5.2.8 on 2025-11-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_searchstrategyversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to Send'), ('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
