# Generated by Django 5.2.8 on 2025-11-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_searchstrategyversion'),
        ('project', '0011_alter_projectphase_current_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPhase',
            fields=[
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='design_phase', serialize=False, to='project.project')),
                ('current_stage', models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalized')], default='RQ_CREATION', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='researchquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='researchquestion',
            name='research_framework',
        ),
        migrations.AlterField(
            model_name='researchquestion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to Send'), ('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='design_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='design.designphase'),
        ),
    ]
