# Generated by Django 5.2.8 on 2025-11-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_designphase_remove_researchquestion_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquestion',
            name='design_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='design.designphase'),
        ),
    ]
