# Generated by Django 5.2.8 on 2025-12-01 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_alter_researchquestion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchstrategy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Search Strategy', 'verbose_name_plural': 'Search Strategies'},
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_search_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='definition',
            field=models.JSONField(blank=True, default=dict, help_text='Definición normalizada (JSON) usada para la ejecución'),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='final_execution_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='last_executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_search_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='total_executions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='total_new_studies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='total_studies_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchstrategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - Building strategy'), ('READY', 'Ready for execution'), ('TESTING', 'Currently testing'), ('FINAL', 'Final version'), ('EXECUTING', 'Currently executing'), ('COMPLETED', 'Execution completed'), ('FAILED', 'Execution failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='searchstrategy',
            index=models.Index(fields=['research_question', '-created_at'], name='design_sear_researc_b275bd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchstrategy',
            index=models.Index(fields=['status'], name='design_sear_status_476864_idx'),
        ),
        migrations.AlterModelTable(
            name='searchstrategy',
            table='design_search_strategy',
        ),
    ]
