# Generated by Django 5.2.8 on 2025-11-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0024_alter_researchquestion_design_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='project_keyword',
        ),
        migrations.DeleteModel(
            name='ProjectKeyword',
        ),
    ]
