# Generated by Django 5.2.8 on 2025-11-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_remove_keyword_project_keyword_delete_projectkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True)),
                ('design_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='design.designphase')),
            ],
            options={
                'unique_together': {('design_phase', 'term')},
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='project_keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.projectkeyword'),
        ),
    ]
