# Generated by Django 5.2.8 on 2025-11-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0026_projectkeyword_keyword_project_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='project_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.projectkeyword'),
        ),
    ]
