# Generated by Django 5.2.8 on 2025-12-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0027_alter_keyword_project_keyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibilitycriterion',
            old_name='suggester',
            new_name='researcher',
        ),
        migrations.RemoveField(
            model_name='eligibilitycriterion',
            name='project',
        ),
        migrations.AddField(
            model_name='eligibilitycriterion',
            name='design_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='design.designphase'),
        ),
        migrations.AddField(
            model_name='eligibilitycriterion',
            name='last_modified_by',
            field=models.ForeignKey(help_text='User who last modified the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eligibilitycriterion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilitycriterion',
            name='reviewed_by',
            field=models.ForeignKey(help_text='User who reviewed the criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='last_modified_by',
            field=models.ForeignKey(help_text='User who last modified the research question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Owner who reviewed the research question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='last_modified_by',
            field=models.ForeignKey(help_text='User who last modified the strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Owner who reviewed the search strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
