# Generated by Django 5.2.8 on 2025-12-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0028_rename_suggester_eligibilitycriterion_researcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriterion',
            name='design_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='design.designphase'),
        ),
    ]
