# Generated by Django 5.2.8 on 2025-12-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0029_alter_eligibilitycriterion_design_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchstrategy',
            name='name',
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='json_definition',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='searchstrategy',
            name='total_studies_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchstrategyversion',
            name='json_definition',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='searchstrategy',
            name='research_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_strategies', to='design.researchquestion'),
        ),
        migrations.AlterField(
            model_name='searchstrategy',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Who reviewed the search strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchstrategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
