# Generated by Django 5.2.8 on 2025-12-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0030_remove_searchstrategy_name_searchstrategy_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstrategyversion',
            name='total_found',
            field=models.PositiveIntegerField(default=0, help_text='Number of studies found with this strategy'),
        ),
        migrations.AlterField(
            model_name='searchstrategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
