# Generated by Django 5.2.8 on 2025-12-01 00:40

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0024_alter_searchstrategy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchExecutionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la ejecución', primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de ejecución')),
                ('translated_queries', models.JSONField(blank=True, default=dict, help_text='Queries traducidas por proveedor (salida de TranslationService)')),
                ('results_count', models.IntegerField(default=0, help_text='Número total de estudios encontrados en esta ejecución')),
                ('new_studies_count', models.IntegerField(default=0, help_text='Número de estudios nuevos (no duplicados)')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='SUCCESS', help_text='Estado de la ejecución', max_length=20)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detalles de errores por proveedor si status != SUCCESS')),
                ('executed_by', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la búsqueda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_searches', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(help_text='Estrategia que se ejecutó (desde design.SearchStrategy)', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='design.searchstrategy')),
            ],
            options={
                'verbose_name': 'Search Execution',
                'verbose_name_plural': 'Search Executions',
                'db_table': 'acquisition_search_execution',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_new', models.BooleanField(default=True, help_text='True si este estudio es nuevo en esta ejecución (no duplicado)')),
                ('providers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Lista de proveedores que retornaron este estudio en esta ejecución', size=None)),
                ('rank_position', models.IntegerField(blank=True, help_text='Posición en resultados (para análisis de relevancia)', null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se vinculó este estudio a la ejecución')),
                ('execution', models.ForeignKey(help_text='Ejecución de búsqueda', on_delete=django.db.models.deletion.CASCADE, to='acquisition.searchexecutionmodel')),
            ],
            options={
                'verbose_name': 'Execution-Study Link',
                'verbose_name_plural': 'Execution-Study Links',
                'db_table': 'acquisition_execution_study',
            },
        ),
        migrations.CreateModel(
            name='StudyModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del estudio (UUID)', primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Título del estudio')),
                ('link', models.URLField(help_text='URL al estudio en la fuente original', max_length=500)),
                ('source', models.CharField(help_text='Fuente académica (Scopus, IEEE Xplore, etc.)', max_length=100)),
                ('doi', models.CharField(blank=True, db_index=True, help_text='Digital Object Identifier', max_length=200, null=True)),
                ('status', models.CharField(db_index=True, default='discovered', help_text='Estado del estudio en el workflow (discovered, enriched, downloaded, failed)', max_length=20)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Lista de autores', null=True, size=None)),
                ('abstract', models.TextField(blank=True, help_text='Resumen del estudio', null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, help_text='Año de publicación', null=True)),
                ('journal', models.CharField(blank=True, help_text='Nombre de la revista/conferencia', max_length=300, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Palabras clave', null=True, size=None)),
                ('pdf_path', models.CharField(blank=True, help_text='Ruta al archivo PDF descargado', max_length=500, null=True)),
                ('pdf_source', models.CharField(blank=True, help_text='Fuente desde donde se obtuvo el PDF', max_length=100, null=True)),
                ('download_status', models.CharField(blank=True, help_text='Estado de disponibilidad del PDF (texto_completo_disponible, no_disponible, pendiente)', max_length=50, null=True)),
                ('consolidation_status', models.CharField(blank=True, help_text='Estado de calidad de metadatos (completo, parcial, fallido)', max_length=20, null=True)),
                ('field_origins', models.JSONField(blank=True, default=dict, help_text="Trazabilidad de origen de cada campo (ej: {'doi': 'manual', 'title': 'discovery'})")),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de cuándo se descubrió el estudio')),
                ('enriched_at', models.DateTimeField(blank=True, help_text='Timestamp de cuándo se enriquecieron los metadatos', null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='Timestamp de cuándo se descargó el PDF', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Razón de fallo si status=failed', null=True)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'db_table': 'acquisition_study',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['doi'], name='acquisition_doi_a7fad2_idx'), models.Index(fields=['status'], name='acquisition_status_a5df28_idx'), models.Index(fields=['year'], name='acquisition_year_f6b04e_idx'), models.Index(fields=['source', 'title'], name='acquisition_source_43e6d1_idx')],
            },
        ),
        migrations.AddField(
            model_name='searchexecutionmodel',
            name='studies',
            field=models.ManyToManyField(help_text='Estudios encontrados en esta ejecución', related_name='executions', through='acquisition.ExecutionStudy', to='acquisition.studymodel'),
        ),
        migrations.AddField(
            model_name='executionstudy',
            name='study',
            field=models.ForeignKey(help_text='Estudio encontrado', on_delete=django.db.models.deletion.CASCADE, to='acquisition.studymodel'),
        ),
        migrations.AddIndex(
            model_name='searchexecutionmodel',
            index=models.Index(fields=['strategy', '-executed_at'], name='acquisition_strateg_073e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchexecutionmodel',
            index=models.Index(fields=['executed_by', '-executed_at'], name='acquisition_execute_3e30f0_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstudy',
            index=models.Index(fields=['execution', 'is_new'], name='acquisition_executi_d70717_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstudy',
            index=models.Index(fields=['study'], name='acquisition_study_i_d65d4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executionstudy',
            unique_together={('execution', 'study')},
        ),
    ]
