# Generated by Django 5.2.8 on 2025-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodel',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Número de páginas del PDF descargado', null=True),
        ),
    ]
