# Generated by Django 5.2.7 on 2025-11-24 14:35

import apps.extraction.domain.value_objects.extraction_status
import apps.extraction.domain.value_objects.tag_type
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=20)),
                ('type', models.CharField(choices=[('deductive', 'deductive'), ('inductive', 'inductive'), ('personal', 'personal')], default=apps.extraction.domain.value_objects.tag_type.TagType['DEDUCTIVE'], max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(help_text='Project context ID')),
                ('created_by_user_id', models.IntegerField(help_text='User ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20)),
            ],
            options={
                'db_table': 'extraction_tag',
            },
        ),
        migrations.CreateModel(
            name='ExtractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.BigIntegerField(db_index=True, help_text='ID del estudio en el servicio de Acquisition/Studies')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Done', 'Done')], default=apps.extraction.domain.value_objects.extraction_status.ExtractionStatus['PENDING'], max_length=20)),
                ('extraction_order', models.PositiveSmallIntegerField(default=1, help_text='Orden de extracción (1=primera, 2=segunda en double extraction)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extraction_extraction',
            },
        ),
        migrations.CreateModel(
            name='ExtractionPhaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, help_text='ID del proyecto en el servicio de Projects', unique=True)),
                ('mode', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', help_text='Modo de extracción: simple, doble o triple', max_length=20)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('AutoClosed', 'AutoClosed')], default='Inactive', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha de inicio de la fase', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha de cierre de la fase', null=True)),
                ('auto_close', models.BooleanField(default=False, help_text='Cerrar automáticamente al llegar a end_date')),
                ('allow_late_submissions', models.BooleanField(default=False, help_text='Permitir extracciones después de end_date')),
                ('min_quotes_required', models.PositiveIntegerField(default=1, help_text='Mínimo de quotes requeridas por extracción')),
                ('max_quotes_per_extraction', models.PositiveIntegerField(default=100, help_text='Máximo de quotes por extracción')),
                ('requires_approval', models.BooleanField(default=False, help_text='Las extracciones completadas requieren aprobación del owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extraction Phase',
                'verbose_name_plural': 'Extraction Phases',
                'db_table': 'extraction_phase',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_id', 'status'], name='extraction__project_a4a5f0_idx'), models.Index(fields=['status', 'end_date'], name='extraction__status_761102_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_portion', models.TextField()),
                ('location_data', models.JSONField(blank=True, help_text='Ubicación estructurada: {page, text_location, coordinates}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='extraction.extractionmodel')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='quotes', to='extraction.tagmodel')),
            ],
            options={
                'db_table': 'extraction_quote',
            },
        ),
        migrations.AddIndex(
            model_name='extractionmodel',
            index=models.Index(fields=['study_id', 'assigned_to'], name='extraction__study_i_97af25_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionmodel',
            index=models.Index(fields=['study_id', 'extraction_order'], name='extraction__study_i_13a575_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionmodel',
            constraint=models.UniqueConstraint(fields=('study_id', 'assigned_to'), name='unique_study_user_extraction'),
        ),
        migrations.AddIndex(
            model_name='quotemodel',
            index=models.Index(fields=['extraction', 'created_at'], name='extraction__extract_b2bcfe_idx'),
        ),
    ]
