# Generated by Django 5.2.8 on 2025-12-17 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisition', '0001_initial'),
        ('design', '0001_initial'),
        ('project', '0002_project_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(choices=[('CONFIG', 'Configuración'), ('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='CONFIG', max_length=10, verbose_name='Estado de la Fase')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_phases', to='project.project', verbose_name='Proyecto Relacionado')),
            ],
            options={
                'verbose_name': 'Fase de Extracción',
                'verbose_name_plural': 'Fases de Extracción',
            },
        ),
        migrations.CreateModel(
            name='PaperExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado')], default='PENDING', max_length=15, verbose_name='Estado de la Extracción')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta o URL del Documento')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_extractions', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('extraction_phase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers_to_extract', to='extraction.extractionphase', verbose_name='Fase de Extracción')),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_extractions', to='acquisition.studymodel', verbose_name='Estudio Relacionado (Acquisition)')),
            ],
            options={
                'verbose_name': 'Extracción de Paper',
                'verbose_name_plural': 'Extracciones de Papers',
                'unique_together': {('study', 'extraction_phase')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Etiqueta')),
                ('color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe ser un código hexadecimal válido (e.g., #FF00AA).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color Hexadecimal')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Es Obligatoria')),
                ('type', models.CharField(choices=[('DEDUCTIVE', 'Deductiva'), ('INDUCTIVE', 'Inductiva')], default='DEDUCTIVE', max_length=10, verbose_name='Tipo de Etiqueta')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10, verbose_name='Estado de Aprobación')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], default='PUBLIC', max_length=10, verbose_name='Visibilidad')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('extraction_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='extraction.extractionphase', verbose_name='Fase de Extracción')),
                ('rq_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='design.researchquestion', verbose_name='Pregunta de Investigación Relacionada')),
            ],
            options={
                'unique_together': {('extraction_phase', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('text_fragment', models.TextField(blank=True, null=True, verbose_name='Fragmento de Texto Extraído')),
                ('location', models.JSONField(default=dict, verbose_name='Ubicación (Página, Párrafo, etc.)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('paper_extraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='extraction.paperextraction', verbose_name='Paper de Origen')),
                ('tags', models.ManyToManyField(related_name='quotes', to='extraction.tag', verbose_name='Etiquetas Aplicadas')),
            ],
            options={
                'verbose_name': 'Cita de Extracción',
                'verbose_name_plural': 'Citas de Extracción',
                'ordering': ['created_at'],
            },
        ),
    ]
