# Generated by Django 5.2.8 on 2025-11-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PaperExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.IntegerField(db_index=True, unique=True)),
                ('project_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('InProgress', 'En Progreso'), ('Done', 'Completado')], default='Pending', max_length=50)),
                ('assigned_to_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id', 'status'], name='extraction__project_54c9ca_idx'), models.Index(fields=['assigned_to_id', 'status'], name='extraction__assigne_265059_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=50)),
                ('justification', models.TextField(blank=True)),
                ('created_by_id', models.IntegerField(db_index=True, null=True)),
                ('question_id', models.IntegerField(blank=True, db_index=True, help_text='ID de la ResearchQuestion externa', null=True)),
                ('project_id', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('deductive', 'Deductivo'), ('inductive', 'Inductivo')], default='deductive', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='extraction.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_portion', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('researcher_id', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='extraction.paperextraction')),
                ('tags', models.ManyToManyField(blank=True, related_name='quotes', to='extraction.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'project_id', 'question_id'), name='unique_tag_per_context'),
        ),
    ]
