# Generated by Django 5.2.8 on 2026-01-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
    ]
