# Generated by Django 5.2.8 on 2025-11-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('configuration', 'Configuración'), ('active', 'Activa'), ('closed', 'Cerrada')], default='configuration', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_close', models.BooleanField(default=False, help_text='Si True, la fase se cierra automáticamente al llegar a end_date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('configured_by_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Extraction Phase',
                'verbose_name_plural': 'Extraction Phases',
            },
        ),
        migrations.CreateModel(
            name='PaperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.IntegerField(db_index=True)),
                ('researcher_id', models.IntegerField(db_index=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('extraction_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='extraction.extractionphase')),
            ],
            options={
                'indexes': [models.Index(fields=['researcher_id', 'extraction_phase'], name='extraction__researc_80c268_idx')],
                'unique_together': {('extraction_phase', 'study_id')},
            },
        ),
    ]
