# Generated by Django 5.2.8 on 2026-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionphase',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='¿Es Activa?'),
        ),
    ]
