# Generated by Django 5.2.8 on 2026-01-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_alter_tag_options'),
    ]

    operations = [        migrations.RunSQL(
            # Renombrar la columna
            'ALTER TABLE extraction_tag RENAME COLUMN question_id TO rq_related_id;',
            # Revertir si es necesario
            'ALTER TABLE extraction_tag RENAME COLUMN rq_related_id TO question_id;'
        ),    ]
