# Generated by Django 5.2.8 on 2025-12-08 13:20

from django.db import migrations, models


def clear_extraction_data(apps, schema_editor):
    """
    Clear all existing PaperExtraction records and related Quote records.
    This is necessary because we cannot convert Integer IDs to UUIDs.
    """
    PaperExtraction = apps.get_model('extraction', 'PaperExtraction')
    Quote = apps.get_model('extraction', 'Quote')
    
    # Clear quotes first (foreign key constraint)
    Quote.objects.all().delete()
    # Then clear extractions
    PaperExtraction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_extractionphase_paperassignment'),
    ]

    operations = [
        # Step 1: Clear existing data to avoid cast errors
        migrations.RunPython(clear_extraction_data, reverse_code=migrations.RunPython.noop),
        
        # Step 2: Remove the old integer field
        migrations.RemoveField(
            model_name='paperextraction',
            name='study_id',
        ),
        
        # Step 3: Add the new UUID field
        migrations.AddField(
            model_name='paperextraction',
            name='study_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
