# Generated by Django 5.2.8 on 2026-01-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_remove_designphase_fecha_inicio_creacion_pregunta_and_more'),
        ('extraction', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rq_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='design.researchquestion', verbose_name='Pregunta de Investigación Relacionada'),
        ),
    ]
