# Generated by Django 5.2.8 on 2026-01-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='question',
            new_name='rq_related',
        ),
    ]
