# Generated by Django 5.2.8 on 2026-01-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='workload_hours',
            field=models.PositiveIntegerField(default=0, help_text='Weekly workload hours for this researcher in this project'),
        ),
    ]
