# Generated by Django 5.2.8 on 2025-11-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_researchquestion_project_researchquestion_stage'),
        ('project', '0003_stage_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='design.researchframework'),
        ),
    ]
