# Generated by Django 5.2.8 on 2025-11-18 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_research_framework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
        migrations.CreateModel(
            name='ResearchFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_global', models.BooleanField(default=False)),
                ('total_fields', models.PositiveIntegerField(default=0)),
                ('fields', models.JSONField(default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_frameworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='research_framework',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project.researchframework'),
        ),
    ]
