# Generated by Django 5.2.8 on 2025-11-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_alter_researchquestion_research_framework_and_more'),
        ('project', '0005_remove_stage_closed_by_remove_stage_opened_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AlterUniqueTogether(
            name='researchframework',
            unique_together={('name', 'assigned_by')},
        ),
    ]
