# Generated by Django 5.2.8 on 2025-11-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_delete_stage_alter_researchframework_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchframework',
            old_name='fields',
            new_name='fields_data',
        ),
        migrations.AlterField(
            model_name='researchframework',
            name='assigned_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='custom_frameworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
