# Generated by Django 5.2.8 on 2025-11-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_fields_researchframework_fields_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchframework',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='researchframework',
            name='total_fields',
        ),
    ]
