# Generated by Django 5.2.8 on 2025-11-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_researchframework_is_global_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('DESIGN', 'Diseño (Preguntas y Criterios)')], max_length=20)),
                ('current_stage', models.CharField(choices=[('CREATION', 'Research Question Creation'), ('DISCUSSION', 'Discussion'), ('FINISHED', 'Finalizado')], default='CREATION', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='project.project')),
            ],
            options={
                'unique_together': {('project', 'phase_type')},
            },
        ),
    ]
