# Generated by Django 5.2.8 on 2025-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='current_stage',
            field=models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalizado')], default='RQ_CREATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_type',
            field=models.CharField(choices=[('DESIGN', 'Design Phase')], max_length=20),
        ),
    ]
