# Generated by Django 5.2.8 on 2025-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectphase_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='current_stage',
            field=models.CharField(choices=[('RQ_CREATION', 'Research Question Creation'), ('RQ_DISCUSSION', 'Discussion'), ('CRITERIA_DEFINITION', 'Eligibility Criteria Definition'), ('SEARCH_STRATEGY', 'Search Strategy Building'), ('FINISHED', 'Finalized')], default='RQ_CREATION', max_length=20),
        ),
    ]
