# Generated by Django 5.2.8 on 2025-11-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_projectphase_current_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
    ]
