# Generated by Django 5.2.8 on 2026-01-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RESEARCH_QUESTION_SUBMITTED_FOR_REVIEW', 'Research Question Submitted for Review'), ('RESEARCH_QUESTION_REVIEWED', 'Research Question Reviewed'), ('SUGGESTION_QUESTION_REJECT', 'Suggestion Question Reject'), ('CRITERION_APPROVED', 'Eligibility Criterion Approved'), ('CRITERION_REJECTED', 'Eligibility Criterion Rejected'), ('STRATEGY_APPROVED', 'Search Strategy Approved'), ('STRATEGY_REJECTED', 'Search Strategy Rejected'), ('STAGE_CONSOLIDATED', 'Design Stage Finalized'), ('OWNER_MODIFIED_APPROVED_QUESTION', 'Owner Modified Approved Question in Closed Stage'), ('OWNER_MODIFIED_APPROVED_CRITERION', 'Owner Modified Approved Criterion in Closed Stage'), ('OWNER_MODIFIED_APPROVED_STRATEGY', 'Owner Modified Approved Strategy in Closed Stage'), ('REMINDER', 'Review Reminder')], max_length=50),
        ),
    ]
