# Generated by Django 5.2.8 on 2026-01-11 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_membership_workload_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionPhase',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selection_phase', serialize=False, to='project.project')),
                ('status', models.CharField(choices=[('ON_GOING', 'On Going'), ('FINALIZED', 'Finalized')], default='ON_GOING', max_length=20)),
                ('current_stage', models.CharField(choices=[('OVERVIEW', 'Overview'), ('SCREENING', 'Screening'), ('FULL_TEXT', 'Full-text Screening'), ('DISCUSSION', 'Discussion')], default='OVERVIEW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Selection Phase',
                'verbose_name_plural': 'Selection Phases',
            },
        ),
        migrations.CreateModel(
            name='PaperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(help_text='Study UUID from acquisition module', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_assignments', to=settings.AUTH_USER_MODEL)),
                ('selection_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='selection.selectionphase')),
            ],
            options={
                'verbose_name': 'Paper Assignment',
                'verbose_name_plural': 'Paper Assignments',
                'unique_together': {('selection_phase', 'paper_id', 'researcher')},
            },
        ),
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('stage', models.CharField(choices=[('OVERVIEW', 'Overview'), ('SCREENING', 'Screening'), ('FULL_TEXT', 'Full-text Screening'), ('DISCUSSION', 'Discussion')], help_text='Stage where this decision was made', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Researcher's notes about the decision")),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='selection.paperassignment')),
            ],
            options={
                'verbose_name': 'Paper Review',
                'verbose_name_plural': 'Paper Reviews',
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=255)),
                ('final_decision', models.CharField(choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded'), ('PENDING', 'Pending')], max_length=20)),
                ('resolution_notes', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('selection_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='selection.selectionphase')),
            ],
            options={
                'verbose_name': 'Conflict Resolution',
                'verbose_name_plural': 'Conflict Resolutions',
                'unique_together': {('selection_phase', 'paper_id')},
            },
        ),
    ]
