# Generated by Django 5.2.8 on 2026-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperreview',
            name='criterion_id',
            field=models.CharField(blank=True, help_text='ID of inclusion/exclusion criterion from design phase', max_length=255, null=True),
        ),
    ]
