# Generated by Django 5.2.8 on 2026-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_paperreview_criterion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperreview',
            name='criterion_label',
            field=models.CharField(blank=True, help_text='Human-readable label of the criterion', max_length=500, null=True),
        ),
    ]
