# Generated by Django 5.2.8 on 2026-01-14 18:07
# Manually edited to only add missing fields

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_paperreview_criterion_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ConflictResolution: Add missing fields (stage already exists)
        migrations.AddField(
            model_name='conflictresolution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='resolution_method',
            field=models.CharField(blank=True, choices=[('OWNER_VOTE', 'Owner Vote'), ('THIRD_REVIEWER', 'Third Reviewer')], help_text='How this conflict was/will be resolved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='third_reviewer',
            field=models.ForeignKey(blank=True, help_text='Third reviewer assigned to resolve this conflict', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_reviewer_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        
        # PaperAssignment: Add missing field (stage already exists)
        migrations.AddField(
            model_name='paperassignment',
            name='is_third_reviewer',
            field=models.BooleanField(default=False, help_text='True if this assignment is for discrepancy resolution'),
        ),
        
        # AlterField operations for ConflictResolution
        migrations.AlterField(
            model_name='conflictresolution',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded'), ('PENDING', 'Pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conflictresolution',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conflictresolution',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflictresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        
        # AlterField for PaperReview and SelectionPhase
        migrations.AlterField(
            model_name='paperreview',
            name='stage',
            field=models.CharField(choices=[('SCREENING_OVERVIEW', 'Screening Overview'), ('SCREENING', 'Screening'), ('SCREENING_DISCUSSION', 'Screening Discussion'), ('FULLTEXT_OVERVIEW', 'Full-text Overview'), ('FULLTEXT', 'Full-text Review'), ('FULLTEXT_DISCUSSION', 'Full-text Discussion')], help_text='Stage where this decision was made', max_length=20),
        ),
        migrations.AlterField(
            model_name='selectionphase',
            name='current_stage',
            field=models.CharField(choices=[('SCREENING_OVERVIEW', 'Screening Overview'), ('SCREENING', 'Screening'), ('SCREENING_DISCUSSION', 'Screening Discussion'), ('FULLTEXT_OVERVIEW', 'Full-text Overview'), ('FULLTEXT', 'Full-text Review'), ('FULLTEXT_DISCUSSION', 'Full-text Discussion')], default='SCREENING_OVERVIEW', max_length=30),
        ),
        
        # Note: unique_together constraints will be handled manually via RunSQL if needed
        # The model's Meta.unique_together will be used by Django for new records
    ]
