# Generated by Django 5.2.8 on 2026-01-14 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_alter_conflictresolution_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conflictresolution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paperassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='stage',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('FULLTEXT', 'Full-text')], default='SCREENING', max_length=20),
        ),
        migrations.AddField(
            model_name='paperassignment',
            name='stage',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('FULLTEXT', 'Full-text')], default='SCREENING', max_length=20),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_fulltext_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_fulltext_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_fulltext_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_metadata_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_metadata_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='discussion_metadata_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_overview_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_overview_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_overview_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_screening_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_screening_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='fulltext_screening_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='screening_metadata_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='screening_metadata_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionphase',
            name='screening_metadata_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conflictresolution',
            unique_together={('selection_phase', 'paper_id', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='paperassignment',
            unique_together={('selection_phase', 'paper_id', 'researcher', 'stage')},
        ),
    ]
